name: 'Terraform Discard'
on:
  push:
    branches:
      - main
env:
  TF_CLOUD_ORGANIZATION: "melanmeg"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "test-api-workspace"
  CONFIG_DIRECTORY: "./"
jobs:
  terraform:
    if: github.repository != 'megutamago/test-api-workspace'
    name: "Terraform Discard"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Discard
        uses: hashicorp/tfc-workflows-github/actions/discard-run@v1.0.4
        id: discard
        with:
          run: ${{ steps.create-run.outputs.run_id }}
          comment: "Discarded from GitHub Actions CI"